#!/bin/sh
# Copyright 2024 Erik Ben Heckman <erik@heckman.ca>
# https://git.heckman.ca/sde  SPDX-License-Identifier: MIT


# remap  v0.3.0  (formerly sde)


# Map each regular-expression match with the result of a command.

# Usage: remap <REGEX> [<SHELL-STATEMENT>]
#        remap [-h|--help|--version]
#
# Reads from STDIN and writes to STDOUT, replacing every match of the regular
# expression with the result of <SHELL-STATEMENT> after replacing all
# occurrences of $& in <SHELL-STATEMENT> with the contents of the match.
#
# If <SHELL-STATEMENT> is omitted, then matches are deleted.
#
# on Unix-like systems <SHELL-STATEMENT> is typically interpreted by /bin/sh,
# or whatever else perl is configured to use as the default system shell.
#
# If this script is being called from bash, and /bin/sh invokes bash being run
# in POSIX mode, then <SHELL-STATEMENT> may include exported functions.
# This functionality is not very well tested.

#--take care editing the header, it's parsed:
# usage uses everything between 'Usage' and the first blank line that follows
usage(){ <"$0" sed -E '/Usage/,/^ *$/!d;/^ *$/q;s/^#( |$)//' ; }
# version uses the third field of the first line containing '# sde'
version(){ awk '/^# *sde/{print $3;exit}' "$0" ; }

case "$1" in
--version) version ;;
-h|--help) usage ;;
*)
	perl -pe 's/'"$1"'/`'"$2"'`/ge'
	;;
esac
